2024-04-19 05:02:00,072 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:02,012 - INFO - Supplier migration complete. Migrated: 5, Failed: 0
2024-04-19 05:02:02,014 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:03,294 - INFO - Unit of Measurement migration complete. Migrated: 50, Failed: 0
2024-04-19 05:02:03,296 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:04,225 - INFO - Item Category migration complete. Migrated: 5, Failed: 0
2024-04-19 05:02:04,228 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:05,028 - INFO - Item Type migration complete. Migrated: 75, Failed: 0
2024-04-19 05:02:05,029 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:06,094 - ERROR - Failed to migrate item 'Smuth capsule': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,096 - ERROR - Failed to migrate item 'Snap IT': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,098 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:06,118 - ERROR - Failed to migrate item 'Spasmopic': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,211 - ERROR - Failed to migrate item 'Stamlo 10': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,212 - ERROR - Failed to migrate item 'Stamlo 5': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,213 - ERROR - Failed to migrate item 'Stemetil MD': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,215 - ERROR - Failed to migrate item 'Tazloc H': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,217 - ERROR - Failed to migrate item 'Telekast L kid': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,218 - ERROR - Failed to migrate item 'Telsartan 20': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,220 - ERROR - Failed to migrate item 'Telsartan 40': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,221 - ERROR - Failed to migrate item 'Telsartan H': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,222 - ERROR - Failed to migrate item 'Telsartan H 80': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,224 - ERROR - Failed to migrate item 'Tenovate': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,225 - ERROR - Failed to migrate item 'Tenovate M': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,226 - ERROR - Failed to migrate item 'Torex jr': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,228 - ERROR - Failed to migrate item 'Trabest Tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,229 - ERROR - Failed to migrate item 'VDM Forte': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,231 - ERROR - Failed to migrate item 'VDM kit': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,232 - ERROR - Failed to migrate item 'Venflon 26 G': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,233 - ERROR - Failed to migrate item 'Vertigon tab': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,235 - ERROR - Failed to migrate item 'Vertin OD': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,236 - ERROR - Failed to migrate item 'Vertin 24': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,238 - ERROR - Failed to migrate item 'Vilnip M': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,239 - ERROR - Failed to migrate item 'Vitcee': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,240 - ERROR - Failed to migrate item 'Zeet expectorant': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,242 - ERROR - Failed to migrate item 'Zerodol PG 75': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,243 - ERROR - Failed to migrate item 'Zerodol SP': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,244 - ERROR - Failed to migrate item 'Zerodol th 4mg': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,245 - ERROR - Failed to migrate item 'Zolfresh 10mg': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,247 - ERROR - Failed to migrate item 'Zolfresh 5mg': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,248 - ERROR - Failed to migrate item 'Zyworm Suspension': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,250 - ERROR - Failed to migrate item 'Zyworm Tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,252 - ERROR - Failed to migrate item 'Hyrax 25': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,253 - ERROR - Failed to migrate item 'Rantop Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,255 - ERROR - Failed to migrate item 'Azito Tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,256 - ERROR - Failed to migrate item 'Absorbent Cotton Wool': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,257 - ERROR - Failed to migrate item 'Calpol 125mg': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,258 - ERROR - Failed to migrate item 'Calpol 250mg': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,260 - ERROR - Failed to migrate item 'Oralhex Mouth Wash': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,261 - ERROR - Failed to migrate item 'Sazotel AM': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,262 - ERROR - Failed to migrate item 'Omegadale Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,263 - ERROR - Failed to migrate item 'Rekool - L': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,264 - ERROR - Failed to migrate item 'Pregabalin 75 mg': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,265 - ERROR - Failed to migrate item 'Calpol Drop': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,266 - ERROR - Failed to migrate item 'AB Cold Tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,267 - ERROR - Failed to migrate item 'Ab Cold La Tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,269 - ERROR - Failed to migrate item 'AB Cold Suspension': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,270 - ERROR - Failed to migrate item 'Ab Vito 12 G': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,271 - ERROR - Failed to migrate item 'Ab Vito 9g': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,273 - ERROR - Failed to migrate item 'Ab Vito Woman': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,274 - ERROR - Failed to migrate item 'Abpent 40 Injection': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,275 - ERROR - Failed to migrate item 'Aciclovir 5% Ointment / Herperax Oint': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,276 - ERROR - Failed to migrate item 'Adaqueen C Gel': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,277 - ERROR - Failed to migrate item 'Aziluk 500': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,279 - ERROR - Failed to migrate item 'Brismox -BR Eye Drops': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,280 - ERROR - Failed to migrate item 'Brismox Eye Ointment': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,281 - ERROR - Failed to migrate item 'Brismox Eye Solution': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,282 - ERROR - Failed to migrate item 'Butanid 0.5mg': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,283 - ERROR - Failed to migrate item 'Canpara - SP': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,284 - ERROR - Failed to migrate item 'Canpara Suspension': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,285 - ERROR - Failed to migrate item 'Car 10': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,287 - ERROR - Failed to migrate item 'Clonazole Powder 100gm': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,288 - ERROR - Failed to migrate item 'Closat -GM Skin cream': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,289 - ERROR - Failed to migrate item 'Codimax - T Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,291 - ERROR - Failed to migrate item 'Crandon Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,292 - ERROR - Failed to migrate item 'Crepe bandage 7.50cm': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,294 - ERROR - Failed to migrate item 'Defkinz 6': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,295 - ERROR - Failed to migrate item 'Dengue test kits': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,297 - ERROR - Failed to migrate item 'Deumac 2.5ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,298 - ERROR - Failed to migrate item 'Esorus -LS': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,300 - ERROR - Failed to migrate item 'Face Lite Gel 20 gm': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,306 - ERROR - Failed to migrate item 'Ferokinz 3D': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,310 - ERROR - Failed to migrate item 'Filter paper': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,312 - ERROR - Failed to migrate item 'Glucometer Test Strips (Dr ONDIN)': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,313 - ERROR - Failed to migrate item 'Graso 1000': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,315 - ERROR - Failed to migrate item 'Grisophen - Cet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,317 - ERROR - Failed to migrate item 'Haemocor D/cyameter': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,318 - ERROR - Failed to migrate item 'HT Zyme xt syr': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,319 - ERROR - Failed to migrate item 'I-Liv DS Syrup 225ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,321 - ERROR - Failed to migrate item 'I-Liv Syrup 100 ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,323 - ERROR - Failed to migrate item 'Indclav 375': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,324 - ERROR - Failed to migrate item 'Isopearl - 20': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,326 - ERROR - Failed to migrate item 'Isopearl- 10': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,328 - ERROR - Failed to migrate item 'Justnac Eye Drops': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,329 - ERROR - Failed to migrate item 'KTZ Tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,330 - ERROR - Failed to migrate item 'L- Nin': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,331 - ERROR - Failed to migrate item 'L- Nin M': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,333 - ERROR - Failed to migrate item 'Lancets (ONDIN)': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,334 - ERROR - Failed to migrate item 'Lensokinz- 15 Tab': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,335 - ERROR - Failed to migrate item 'Livtears Ultra Eye Drops': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,337 - ERROR - Failed to migrate item 'Lovex 500': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,338 - ERROR - Failed to migrate item 'Lycozip 19 Cap': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,339 - ERROR - Failed to migrate item 'Lycozip XT Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,341 - ERROR - Failed to migrate item 'M Lite Plus Cream': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,342 - ERROR - Failed to migrate item 'Mecovit Plus': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,343 - ERROR - Failed to migrate item 'Methilovit PG': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,345 - ERROR - Failed to migrate item 'Milocal - Z Suspension': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,346 - ERROR - Failed to migrate item 'Mixocal 500': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,348 - ERROR - Failed to migrate item 'Molori - L Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,349 - ERROR - Failed to migrate item 'Olokick Eye Drops': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,350 - ERROR - Failed to migrate item 'Omegawave E': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,352 - ERROR - Failed to migrate item 'Onin MD - 4': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,353 - ERROR - Failed to migrate item 'Oxyxip DHA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,354 - ERROR - Failed to migrate item 'Oxyzip CZS': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,356 - ERROR - Failed to migrate item 'Oxyzip XT syr': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,358 - ERROR - Failed to migrate item 'Perish Cream': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,359 - ERROR - Failed to migrate item 'Ret Life': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,360 - ERROR - Failed to migrate item 'Ribzyn 20': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,362 - ERROR - Failed to migrate item 'Ribzyn DSR': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,363 - ERROR - Failed to migrate item 'Ribzyn IT': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,365 - ERROR - Failed to migrate item 'Ribzyn LS': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,366 - ERROR - Failed to migrate item 'Roller Bandage 7.5 cm': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,368 - ERROR - Failed to migrate item 'Ronryl - DX': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,369 - ERROR - Failed to migrate item 'Ronryl- TM Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,371 - ERROR - Failed to migrate item 'Sodium citrate 3.8%': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,373 - ERROR - Failed to migrate item 'Spasnil- D Tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,374 - ERROR - Failed to migrate item 'Sucragyl O': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,375 - ERROR - Failed to migrate item 'Surgical Blade no 16': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,377 - ERROR - Failed to migrate item 'Surgicare Sterile gloves 6': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,378 - ERROR - Failed to migrate item 'Tam MF': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,380 - ERROR - Failed to migrate item 'Terbaz tablet': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,381 - ERROR - Failed to migrate item 'Test tubes 10ml 10x 125': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,382 - ERROR - Failed to migrate item 'Tret A Cream': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,383 - ERROR - Failed to migrate item 'Udiaz - 300': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,385 - ERROR - Failed to migrate item 'Ulcer Cure gel': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,387 - ERROR - Failed to migrate item 'Ulcer D 450 ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,389 - ERROR - Failed to migrate item 'Ultonic syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,390 - ERROR - Failed to migrate item 'Unsterile gloves medium (Care View)': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,392 - ERROR - Failed to migrate item 'Urispas': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,393 - ERROR - Failed to migrate item 'Walact Dry Syrup': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,395 - ERROR - Failed to migrate item 'Waylact capsule': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,397 - ERROR - Failed to migrate item 'ABO grouping': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,399 - ERROR - Failed to migrate item 'Albumin ERBA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,400 - ERROR - Failed to migrate item 'ALP ERBA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,402 - ERROR - Failed to migrate item 'Billirubin ERBA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,404 - ERROR - Failed to migrate item 'Blood mp (ICT)': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,406 - ERROR - Failed to migrate item 'Calcium ERBA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,408 - ERROR - Failed to migrate item 'Cholesterol ERBA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,410 - ERROR - Failed to migrate item 'Cotton gauze cloth(Natura )': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,412 - ERROR - Failed to migrate item 'Cotton Roll 500gm': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,413 - ERROR - Failed to migrate item 'Coverslip': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,415 - ERROR - Failed to migrate item 'Creatinine ERBA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,417 - ERROR - Failed to migrate item 'Dispo van 10 ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,419 - ERROR - Failed to migrate item 'Dispo van 2 ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,421 - ERROR - Failed to migrate item 'Dispo Van 3ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,422 - ERROR - Failed to migrate item 'Dispo van 5ml': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,425 - ERROR - Failed to migrate item 'Distilled water': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,426 - ERROR - Failed to migrate item 'Glass slides': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,428 - ERROR - Failed to migrate item 'Glucose ERBA': UNIQUE constraint failed: item_item.item_code
2024-04-19 05:02:06,681 - INFO - Item migration complete. Migrated: 294, Failed: 149
2024-04-19 05:02:06,682 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:06,789 - INFO - Supplier migration complete. Migrated: 5, Failed: 0
2024-04-19 05:02:06,800 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:07,368 - INFO - Person Type migration complete. Migrated: 4, Failed: 0
2024-04-19 05:02:07,374 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:07,530 - INFO - Unit of Measurement migration complete. Migrated: 50, Failed: 0
2024-04-19 05:02:07,532 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:08,235 - INFO - Item Category migration complete. Migrated: 5, Failed: 0
2024-04-19 05:02:08,243 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:08,552 - INFO - Person migration complete. Migrated: 385, Failed: 0
2024-04-19 05:02:08,570 - ERROR - Internal Server Error: /setup/
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/setup/views.py", line 10, in list
    return Response(data)
           ^^^^^^^^^^^^^^
TypeError: Response.__init__() takes 1 positional argument but 2 were given
2024-04-19 05:02:09,053 - INFO - Item Type migration complete. Migrated: 75, Failed: 0
2024-04-19 05:02:09,054 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:10,512 - INFO - Item migration complete. Migrated: 443, Failed: 0
2024-04-19 05:02:10,527 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:11,286 - INFO - Person Type migration complete. Migrated: 4, Failed: 0
2024-04-19 05:02:11,289 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 05:02:12,263 - INFO - Person migration complete. Migrated: 385, Failed: 0
2024-04-19 05:02:12,273 - ERROR - Internal Server Error: /setup/
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/setup/views.py", line 10, in list
    return Response(data)
           ^^^^^^^^^^^^^^
TypeError: Response.__init__() takes 1 positional argument but 2 were given
2024-04-19 07:12:40,396 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:12:57,753 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:12:59,460 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:01,002 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:02,511 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:04,023 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:05,507 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:08,051 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:09,604 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:38,360 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/medicine/models.py changed, reloading.
2024-04-19 07:13:48,081 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/medicine/models.py changed, reloading.
2024-04-19 07:13:52,747 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:55,305 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:13:57,835 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:14:11,298 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:08,232 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:10,006 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:11,503 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:15,066 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:24,862 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:44,170 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:45,849 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:50,482 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:51,987 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:15:55,575 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:16:00,502 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:16:02,022 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:16:03,526 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:17,322 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:19,082 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:20,589 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:22,084 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:32,921 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:35,607 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:38,135 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:39,661 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:41,169 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 07:21:47,834 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 08:05:56,784 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 08:06:16,494 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 08:24:31,074 - WARNING - Bad Request: /prescriptions/
2024-04-19 08:24:31,078 - WARNING - Bad Request: /prescriptions/
2024-04-19 12:05:57,791 - WARNING - Not Found: /favicon.ico
2024-04-19 12:05:59,280 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 12:06:01,259 - INFO - Supplier migration complete. Migrated: 5, Failed: 0
2024-04-19 12:06:01,264 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 12:06:02,201 - INFO - Unit of Measurement migration complete. Migrated: 50, Failed: 0
2024-04-19 12:06:02,202 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 12:06:02,969 - INFO - Item Category migration complete. Migrated: 5, Failed: 0
2024-04-19 12:06:02,972 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 12:06:03,903 - INFO - Item Type migration complete. Migrated: 75, Failed: 0
2024-04-19 12:06:03,904 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 12:06:05,754 - INFO - Item migration complete. Migrated: 443, Failed: 0
2024-04-19 12:06:05,756 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 12:06:06,899 - INFO - Person Type migration complete. Migrated: 4, Failed: 0
2024-04-19 12:06:06,905 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-04-19 12:06:08,005 - INFO - Person migration complete. Migrated: 385, Failed: 0
2024-04-19 12:06:08,022 - ERROR - Internal Server Error: /setup/
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/setup/views.py", line 10, in list
    return Response(data)
           ^^^^^^^^^^^^^^
TypeError: Response.__init__() takes 1 positional argument but 2 were given
2024-04-19 12:08:16,564 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/person/models.py changed, reloading.
2024-04-19 12:08:34,994 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py changed, reloading.
2024-04-19 14:49:29,789 - ERROR - Error in processing request: Authentication credentials were not provided.
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
2024-04-19 14:49:29,791 - WARNING - Forbidden: /prescriptions/
2024-04-19 14:49:29,794 - ERROR - Error in processing request: Authentication credentials were not provided.
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
2024-04-19 14:49:29,794 - WARNING - Forbidden: /prescriptions/
2024-04-19 16:06:04,382 - ERROR - Error in processing request: Authentication credentials were not provided.
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
2024-04-19 16:06:04,383 - WARNING - Forbidden: /prescriptions/
2024-04-19 16:07:15,595 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,601 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,602 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,608 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,609 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,614 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,615 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,622 - WARNING - Bad Request: /transaction/issue_item/
2024-04-19 16:07:15,668 - ERROR - Error in processing request: Authentication credentials were not provided.
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
2024-04-19 16:07:15,669 - WARNING - Forbidden: /prescriptions/
2024-04-19 16:07:23,069 - ERROR - Error in processing request: Authentication credentials were not provided.
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
2024-04-19 16:07:23,070 - WARNING - Forbidden: /prescriptions/
2024-04-19 16:07:50,224 - ERROR - Error in processing request: Authentication credentials were not provided.
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
2024-04-19 16:07:50,234 - WARNING - Forbidden: /prescriptions/
2024-04-19 16:08:01,736 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py changed, reloading.
2024-04-19 16:08:21,104 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py changed, reloading.
2024-04-19 16:08:29,215 - ERROR - Error in processing request: 'PrescriptionViewSet' object has no attribute 'filterset_class'
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py", line 32, in get_queryset
    return queryset.filter(self.filterset_class(self.request.GET, queryset=queryset, request=self.request).qs)
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrescriptionViewSet' object has no attribute 'filterset_class'
2024-04-19 16:08:29,257 - ERROR - Internal Server Error: /prescriptions/
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py", line 39, in handle_exception
    return super().handle_exception(exc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py", line 32, in get_queryset
    return queryset.filter(self.filterset_class(self.request.GET, queryset=queryset, request=self.request).qs)
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrescriptionViewSet' object has no attribute 'filterset_class'
2024-04-19 16:08:42,795 - INFO - /Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py changed, reloading.
2024-04-19 16:09:02,291 - ERROR - Error in processing request: {'date_and_time': [ErrorDetail(string='Datetime has wrong format. Use one of these formats instead: DD-MM-YYYY hh:mm:ss.', code='invalid')], 'prescribed_item_set': [ErrorDetail(string='This field is required.', code='required')]}
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'date_and_time': [ErrorDetail(string='Datetime has wrong format. Use one of these formats instead: DD-MM-YYYY hh:mm:ss.', code='invalid')], 'prescribed_item_set': [ErrorDetail(string='This field is required.', code='required')]}
2024-04-19 16:09:02,294 - WARNING - Bad Request: /prescriptions/
2024-04-19 16:09:53,091 - ERROR - Error in processing request: {'date_and_time': [ErrorDetail(string='Datetime has wrong format. Use one of these formats instead: DD-MM-YYYY hh:mm:ss.', code='invalid')], 'prescribed_item_set': [ErrorDetail(string='This field is required.', code='required')]}
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'date_and_time': [ErrorDetail(string='Datetime has wrong format. Use one of these formats instead: DD-MM-YYYY hh:mm:ss.', code='invalid')], 'prescribed_item_set': [ErrorDetail(string='This field is required.', code='required')]}
2024-04-19 16:09:53,094 - WARNING - Bad Request: /prescription/
2024-04-19 23:21:55,796 - ERROR - Error in processing request: {'date_and_time': [ErrorDetail(string='Datetime has wrong format. Use one of these formats instead: DD-MM-YYYY hh:mm:ss.', code='invalid')], 'prescribed_item_set': [ErrorDetail(string='This field is required.', code='required')]}
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'date_and_time': [ErrorDetail(string='Datetime has wrong format. Use one of these formats instead: DD-MM-YYYY hh:mm:ss.', code='invalid')], 'prescribed_item_set': [ErrorDetail(string='This field is required.', code='required')]}
2024-04-19 23:21:55,797 - WARNING - Bad Request: /prescription/
2024-04-19 23:27:36,708 - ERROR - Error in processing request: UNIQUE constraint failed: prescription_prescription.code
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: prescription_prescription.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py", line 81, in create
    prescription = Prescription.objects.create(**validated_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: prescription_prescription.code
2024-04-19 23:27:36,716 - ERROR - Internal Server Error: /prescription/
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: prescription_prescription.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py", line 39, in handle_exception
    return super().handle_exception(exc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py", line 81, in create
    prescription = Prescription.objects.create(**validated_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: prescription_prescription.code
2024-04-19 23:31:47,742 - ERROR - Error in processing request: UNIQUE constraint failed: prescription_prescription.code
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: prescription_prescription.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py", line 81, in create
    prescription = Prescription.objects.create(**validated_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/models.py", line 35, in save
    super().save(*args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: prescription_prescription.code
2024-04-19 23:31:47,750 - ERROR - Internal Server Error: /prescription/
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: prescription_prescription.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py", line 39, in handle_exception
    return super().handle_exception(exc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py", line 81, in create
    prescription = Prescription.objects.create(**validated_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/models.py", line 35, in save
    super().save(*args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: prescription_prescription.code
2024-04-19 23:32:15,402 - ERROR - Error in processing request: UNIQUE constraint failed: prescription_prescription.code
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: prescription_prescription.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py", line 81, in create
    prescription = Prescription.objects.create(**validated_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/models.py", line 35, in save
    super().save(*args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: prescription_prescription.code
2024-04-19 23:32:15,410 - ERROR - Internal Server Error: /prescription/
Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: prescription_prescription.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/views.py", line 39, in handle_exception
    return super().handle_exception(exc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/serializers.py", line 81, in create
    prescription = Prescription.objects.create(**validated_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/features/prescription/models.py", line 35, in save
    super().save(*args, **kwargs)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tluanga/Dev/code/current-work/mzu-hc-back/env/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: prescription_prescription.code
